-- [nfnl] fnl/conjure/client/common-lisp/completions.fnl
local _local_1_ = require("conjure.nfnl.module")
local autoload = _local_1_["autoload"]
local define = _local_1_["define"]
local ls = autoload("conjure.lexical-search")
local M = define("conjure.client.common-lisp.completions")
local locals_query = "\n  (defun_header\n    function_name: ((sym_lit) @global.define)*\n    lambda_list:\n      (list_lit\n        ((sym_lit) @local.define)*\n      )\n  )\n  @local.scope\n\n  (defun_header\n    function_name: ((sym_lit) @global.define)*\n    lambda_list:\n     (list_lit\n        (list_lit\n          . (sym_lit) @local.define\n        )\n     )\n  )\n  @local.scope\n\n  (defun) @local.scope\n\n  (list_lit\n    .\n    (sym_lit) @_defvar\n    .\n    (sym_lit) @global.define\n    (#match? @_defvar \"^(cl:)?(defvar|defparameter|defconstant)$\"))\n  @local.scope\n\n  (list_lit\n    .\n    (sym_lit) @_def\n    .\n    (sym_lit) @global.define\n    ((sym_lit) @local.bind)*\n    (list_lit\n       (sym_lit) @local.bind\n    )*\n    (list_lit\n       (list_lit\n         . \n         (sym_lit) @local.bind\n       )\n    )*\n    (#match? @_def \"^(cl:)?(defsetf)$\"))\n  @local.scope\n\n  (list_lit\n    .\n    (sym_lit) @_deftest\n    .\n    (sym_lit) @global.define\n    (#eq? @_deftest \"deftest\"))\n  @local.scope\n\n  (for_clause\n    .\n    (sym_lit) @local.bind\n  )\n\n  (with_clause\n    .\n    (sym_lit) @local.bind\n  )\n\n  (loop_macro)\n  @local.scope\n\n  (list_lit\n    . (sym_lit) @_d\n    . (list_lit . (sym_lit) @local.bind)\n    (#any-of? @_d \"dotimes\"))\n  @local.scope\n\n  (list_lit\n    . (sym_lit) @_d\n    . (list_lit\n         (list_lit\n            . (sym_lit) @local.bind\n         )\n      )\n    (#any-of? @_d \"do\" \"do*\"))\n  @local.scope\n\n  (list_lit\n    . (sym_lit) @_db\n    . (list_lit ((sym_lit) @local.bind)*)\n    (#any-of? @_db \"destructuring-bind\" \"multiple-value-bind\"))\n  @local.scope\n\n  (list_lit\n    . (sym_lit) @_l\n    . (list_lit\n       (list_lit . (sym_lit) @local.bind))\n    (#any-of? @_l \"let\" \"let*\"))\n  @local.scope\n\n  (list_lit\n    . (sym_lit) @_l\n    . (list_lit\n       (list_lit \n         . (sym_lit) @local.bind\n         . (list_lit (sym_lit) @local.bind))\n       @local.scope\n      )\n    (#any-of? @_l \"flet\" \"labels\" \"macrolet\"))\n  @local.scope\n\n  (list_lit\n    . (sym_lit) @_dc\n    . (sym_lit) @global.define\n  (#any-of? @_dc \"defclass\" \"defstruct\"))\n  @local.scope\n"
M["get-lexical-completions"] = function()
  return ls["get-lexical-captures"]("commonlisp", locals_query)
end
return M
